import {getDatabase} from '@/database/database';import {Relationship,now,uuid} from '@/types';
export function relationshipScore(c:{relationship_strength:number;importance:number;last_contact_at?:number|null;next_follow_up_at?:number|null}){const days=c.last_contact_at?Math.max(0,(Date.now()-c.last_contact_at)/86400000):365;const recency=Math.max(0,Math.min(30,30-days/12));const followUp=c.next_follow_up_at&&c.next_follow_up_at>Date.now()?10:0;return Math.round(c.relationship_strength/5*35+c.importance/5*25+recency+followUp)}
export type NetworkGraph={nodes:Record<string,unknown>[];edges:Pick<Relationship,'id'|'contact_a_id'|'contact_b_id'|'strength'|'relationship_type'>[]};
export const NetworkService={
 upsert:async(a:string,b:string,type='other',strength=3)=>{if(a===b)throw Error('A person cannot be connected to themselves');const d=await getDatabase(),t=now();const [x,y]=[a,b].sort();await d.runAsync('INSERT INTO relationships(id,contact_a_id,contact_b_id,relationship_type,strength,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING',uuid(),x,y,type,strength,t,t);await d.runAsync('UPDATE relationships SET strength=?,relationship_type=?,updated_at=? WHERE min(contact_a_id,contact_b_id)=? AND max(contact_a_id,contact_b_id)=? AND deleted_at IS NULL',strength,type,t,x,y);},
 shortestPath:async(fromId:string,toId:string,maxDepth=6)=>{const d=await getDatabase();const rows=await d.getAllAsync<{contact_a_id:string;contact_b_id:string}>('SELECT contact_a_id,contact_b_id FROM relationships WHERE deleted_at IS NULL');const adj=new Map<string,string[]>();for(const r of rows){adj.set(r.contact_a_id,[...(adj.get(r.contact_a_id)??[]),r.contact_b_id]);adj.set(r.contact_b_id,[...(adj.get(r.contact_b_id)??[]),r.contact_a_id]);}const queue=[{id:fromId,path:[fromId]}],seen=new Set([fromId]);while(queue.length){const n=queue.shift()!;if(n.id===toId)return n.path;if(n.path.length-1>=maxDepth)continue;for(const next of adj.get(n.id)??[]){if(!seen.has(next)){seen.add(next);queue.push({id:next,path:[...n.path,next]});}}}return null;},
 graph:async(id:string,depth=2,maxNodes=150):Promise<NetworkGraph>=>{const d=await getDatabase();const nodes=await d.getAllAsync<Record<string,unknown>>('WITH RECURSIVE reach(id,depth) AS (SELECT ?,0 UNION SELECT CASE WHEN r.contact_a_id=reach.id THEN r.contact_b_id ELSE r.contact_a_id END,reach.depth+1 FROM relationships r JOIN reach ON (r.contact_a_id=reach.id OR r.contact_b_id=reach.id) WHERE r.deleted_at IS NULL AND reach.depth<?) SELECT c.* FROM reach JOIN contacts c ON c.id=reach.id WHERE c.deleted_at IS NULL ORDER BY reach.depth,c.first_name LIMIT ?',id,depth,maxNodes);const ids=nodes.map(n=>String(n.id));if(!ids.length)return {nodes:[],edges:[]};const placeholders=ids.map(()=>'?').join(',');const edges=await d.getAllAsync<Pick<Relationship,'id'|'contact_a_id'|'contact_b_id'|'strength'|'relationship_type'>>(`SELECT id,contact_a_id,contact_b_id,strength,relationship_type FROM relationships WHERE deleted_at IS NULL AND contact_a_id IN (${placeholders}) AND contact_b_id IN (${placeholders})`,...ids,...ids);return {nodes,edges};},
 connections:async(id:string,depth=2)=>{const graph=await NetworkService.graph(id,depth);return graph.nodes.filter(c=>c.id!==id);},
 health:(c:{relationship_strength:number;importance:number;last_contact_at?:number|null})=>{const days=c.last_contact_at?Math.floor((Date.now()-c.last_contact_at)/86400000):999;return c.relationship_strength>=4&&c.importance>=4&&days>90?'Dormant':days>180||c.relationship_strength<=2?'Dormant':days>60?'Cooling':'Healthy'}
};
