import * as SQLite from 'expo-sqlite';
import * as SecureStore from 'expo-secure-store';
import {now,uuid} from '@/types';
let db:SQLite.SQLiteDatabase|null=null;
const KEY='networkos.db.key';
const migration=`CREATE TABLE IF NOT EXISTS companies(id TEXT PRIMARY KEY,name TEXT NOT NULL,website TEXT,industry TEXT,city TEXT,country TEXT,description TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER,sync_status TEXT NOT NULL DEFAULT 'local',version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS contacts(id TEXT PRIMARY KEY,first_name TEXT NOT NULL,last_name TEXT,display_name TEXT,job_title TEXT,company_id TEXT,email TEXT,phone TEXT,linkedin_url TEXT,website TEXT,city TEXT,country TEXT,birthday INTEGER,relationship_strength INTEGER NOT NULL DEFAULT 3 CHECK(relationship_strength BETWEEN 1 AND 5),importance INTEGER NOT NULL DEFAULT 3 CHECK(importance BETWEEN 1 AND 5),how_we_met TEXT,met_at TEXT,met_date INTEGER,notes TEXT,last_contact_at INTEGER,next_follow_up_at INTEGER,favorite INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER,sync_status TEXT NOT NULL DEFAULT 'local',version INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(company_id) REFERENCES companies(id));
CREATE TABLE IF NOT EXISTS relationships(id TEXT PRIMARY KEY,contact_a_id TEXT NOT NULL,contact_b_id TEXT NOT NULL,relationship_type TEXT,strength INTEGER NOT NULL DEFAULT 3 CHECK(strength BETWEEN 1 AND 5),context TEXT,notes TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER,sync_status TEXT NOT NULL DEFAULT 'local',version INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(contact_a_id) REFERENCES contacts(id),FOREIGN KEY(contact_b_id) REFERENCES contacts(id),CHECK(contact_a_id<>contact_b_id));
CREATE UNIQUE INDEX IF NOT EXISTS relationships_pair ON relationships(min(contact_a_id,contact_b_id),max(contact_a_id,contact_b_id)) WHERE deleted_at IS NULL;
CREATE TABLE IF NOT EXISTS interactions(id TEXT PRIMARY KEY,contact_id TEXT NOT NULL,type TEXT NOT NULL,title TEXT,description TEXT,interaction_at INTEGER NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER,sync_status TEXT NOT NULL DEFAULT 'local',version INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(contact_id) REFERENCES contacts(id));
CREATE TABLE IF NOT EXISTS tags(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER,sync_status TEXT NOT NULL DEFAULT 'local',version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS contact_tags(contact_id TEXT NOT NULL,tag_id TEXT NOT NULL,PRIMARY KEY(contact_id,tag_id),FOREIGN KEY(contact_id) REFERENCES contacts(id),FOREIGN KEY(tag_id) REFERENCES tags(id));
CREATE TABLE IF NOT EXISTS owner_profile(id TEXT PRIMARY KEY,first_name TEXT NOT NULL,last_name TEXT,email TEXT,phone TEXT,company TEXT,job_title TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS contacts_name ON contacts(first_name,last_name);CREATE INDEX IF NOT EXISTS contacts_company ON contacts(company_id);CREATE INDEX IF NOT EXISTS contacts_followup ON contacts(next_follow_up_at);CREATE INDEX IF NOT EXISTS relationships_a ON relationships(contact_a_id);CREATE INDEX IF NOT EXISTS relationships_b ON relationships(contact_b_id);CREATE INDEX IF NOT EXISTS interactions_contact ON interactions(contact_id,interaction_at);`;
export async function getDatabaseKey(){let key=await SecureStore.getItemAsync(KEY);if(!key){key=uuid()+uuid();await SecureStore.setItemAsync(KEY,key,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY});}return key;}

export async function rotateDatabaseKey(newKey?:string){const d=await getDatabase();const key=newKey??uuid()+uuid();assertSafePragmaKey(key);await d.execAsync(`PRAGMA rekey = '${escapePragmaKey(key)}';`);await SecureStore.setItemAsync(KEY,key,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY});return key;}

function assertSafePragmaKey(key:string){if(!key||key.length<16||key.length>256||/[\0\n\r]/.test(key))throw Error('Invalid database key');}

function escapePragmaKey(key:string){return key.replace(/'/g,"''");}
const migration2=`CREATE TABLE IF NOT EXISTS commitments(id TEXT PRIMARY KEY,contact_id TEXT NOT NULL,text TEXT NOT NULL,due_at INTEGER,completed_at INTEGER,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER,FOREIGN KEY(contact_id) REFERENCES contacts(id));CREATE INDEX IF NOT EXISTS commitments_due ON commitments(due_at,completed_at);`;
const migration3=`CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,name TEXT NOT NULL,event_at INTEGER NOT NULL,location TEXT,notes TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER);CREATE TABLE IF NOT EXISTS event_contacts(event_id TEXT NOT NULL,contact_id TEXT NOT NULL,PRIMARY KEY(event_id,contact_id),FOREIGN KEY(event_id) REFERENCES events(id),FOREIGN KEY(contact_id) REFERENCES contacts(id));CREATE INDEX IF NOT EXISTS events_date ON events(event_at);`;
const migration4=`ALTER TABLE contacts ADD COLUMN phone_norm TEXT;CREATE INDEX IF NOT EXISTS contacts_phone_norm ON contacts(phone_norm);CREATE INDEX IF NOT EXISTS contacts_email_lower ON contacts(email);UPDATE contacts SET phone_norm=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(phone,' ',''),'-',''),'(',''),')',''),'+','') WHERE phone IS NOT NULL;`;
export async function getDatabase(){if(db)return db;const key=await getDatabaseKey();assertSafePragmaKey(key);db=await SQLite.openDatabaseAsync('networkos.db',{useSQLCipher:true} as any);await db.execAsync(`PRAGMA key = '${escapePragmaKey(key)}';`);await db.execAsync(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;`);await db.withTransactionAsync(async()=>{const v=await db!.getFirstAsync<{user_version:number}>('PRAGMA user_version');const version=v?.user_version??0;if(version<1){await db!.execAsync(migration);await db!.execAsync('PRAGMA user_version=1');}if(version<2){await db!.execAsync(migration2);await db!.execAsync('PRAGMA user_version=2');}if(version<3){await db!.execAsync(migration3);await db!.execAsync('PRAGMA user_version=3');}if(version<4){await db!.execAsync(migration4);await db!.execAsync('PRAGMA user_version=4');}});return db;}
export const seedOwner=async(first_name:string,last_name:string)=>{const d=await getDatabase();const existing=await d.getFirstAsync('SELECT id FROM owner_profile');if(!existing)await d.runAsync('INSERT INTO owner_profile(id,first_name,last_name,created_at,updated_at) VALUES(?,?,?,?,?)',uuid(),first_name,last_name,now(),now());};
