import AsyncStorage from '@react-native-async-storage/async-storage';
import {useAppStore} from '@/stores/useAppStore';

export type Language = 'en' | 'tr';
const text = {
  en: {home:'Home',contacts:'Contacts',network:'Network',followUp:'Follow up',more:'More',privateByDesign:'Private by design.',language:'Language',english:'English',turkish:'Türkçe',people:'People',peopleSubtitle:'The people who shape your world.',searchNetwork:'Search your network',noPeople:'No people yet. Add your first connection from Home.',followUpSubtitle:'Small gestures, kept on time.',nothingScheduled:'Nothing scheduled. When someone matters, give the relationship a next step.',seeThread:'See the thread.',choosePerson:'Choose a person below',nearby:'Their nearby connections will appear here.',nowChoose:'Now choose who you want to reach.',realConnections:'Real connections, one person at a time.',profile:'Profile',companies:'Companies',security:'Security & app lock',backup:'Backup & restore',tags:'Tags',about:'About NetworkOS',privateNetwork:'Your network is private.',unlockContinue:'Unlock to continue.',unlockBiometrics:'Unlock with biometrics',keepTheThread:'Keep the thread.',networkToday:'YOUR NETWORK, TODAY',startWithOne:'Start with one person',keepPeopleClose:'Keep the people who matter close enough to act on.',addSomeone:'Add someone you know and build outward from there.',openNetwork:'Open network',strongConnections:(n:number)=>`${n} strong connections`,onboardingTitle:'Your network.\nOrganized.',onboardingSubtitle:'Keep track of the people who matter to you — privately, on this device.',firstName:'Your first name',lastName:'Your last name',startBuilding:'Start building your network',noAccount:'No account. No server. Just your network.',back:'‹ More',cancel:'Cancel',save:'Save',retry:'Retry',encryptedBackup:'Export encrypted backup',restoreBackup:'Restore encrypted backup',csvWarning:'CSV is not encrypted. Anyone with the file can read it.',todayFocus:'Today’s focus',birthdays:'Upcoming birthdays',noBirthdays:'No birthdays in the next 30 days.',statStrong:'Strong',todaySection:'Today',followUpsCount:(n:number)=>`${n} follow-up${n===1?'':'s'}`,followUpPrefix:'Follow up',quietDay:'A quiet day. Your next follow-up will appear here.',recentlyAdded:'Recently added',seeThreadTitle:'See the thread.',shortestPath:'SHORTEST PATH',degreesAway:(n:number)=>`${n} degree${n===1?'':'s'} away`,noConnectionSix:'No connection within six degrees',tryAnother:'Try another person or add the missing relationship.',focusLabel:'FOCUS',findPath:'Find path',profileLink:'Profile ›',chooseStarting:'Choose a starting point',buildMap:'Build a living map from someone you know.',findPerson:'Find a person',connectionDefault:'Connection',setAsDestination:'Set as destination',inNeighborhood:'in this neighborhood',relToday:'Today',relYesterday:'Yesterday',relDaysAgo:(n:number)=>`${n} days ago`,relMonthsAgo:(n:number)=>`${n} months ago`,relYearsAgo:(n:number)=>`${n} years ago`,noContactYet:'No contact yet'},
  tr: {home:'Ana Sayfa',contacts:'Kişiler',network:'Ağ',followUp:'Takip',more:'Daha Fazla',privateByDesign:'Gizlilik için tasarlandı.',language:'Dil',english:'English',turkish:'Türkçe',people:'Kişiler',peopleSubtitle:'Dünyanızı şekillendiren insanlar.',searchNetwork:'Ağınızda ara',noPeople:'Henüz kişi yok. Ana Sayfa’dan ilk bağlantınızı ekleyin.',followUpSubtitle:'Küçük jestleri zamanında yapın.',nothingScheduled:'Planlanmış bir şey yok. Önem verdiğiniz bir ilişkiye sonraki adımı ekleyin.',seeThread:'Bağlantıyı görün.',choosePerson:'Aşağıdan bir kişi seçin',nearby:'Yakındaki bağlantıları burada göreceksiniz.',nowChoose:'Ulaşmak istediğiniz kişiyi seçin.',realConnections:'Gerçek bağlantılar, her seferinde bir kişi.',profile:'Profil',companies:'Şirketler',security:'Güvenlik ve uygulama kilidi',backup:'Yedekleme ve geri yükleme',tags:'Etiketler',about:'NetworkOS hakkında',privateNetwork:'Ağınız gizlidir.',unlockContinue:'Devam etmek için kilidi açın.',unlockBiometrics:'Biyometriyle kilidi aç',keepTheThread:'Bağlantıyı koru.',networkToday:'BUGÜN AĞINIZ',startWithOne:'Bir kişiyle başlayın',keepPeopleClose:'Önem verdiğiniz kişileri harekete geçebilecek kadar yakın tutun.',addSomeone:'Tanıdığınız birini ekleyin ve ağınızı oradan büyütün.',openNetwork:'Ağı aç',strongConnections:(n:number)=>`${n} güçlü bağlantı`,onboardingTitle:'Ağınız.\nDüzenli.',onboardingSubtitle:'Önem verdiğiniz kişileri bu cihazda, gizli olarak takip edin.',firstName:'Adınız',lastName:'Soyadınız',startBuilding:'Ağınızı oluşturmaya başlayın',noAccount:'Hesap yok. Sunucu yok. Sadece ağınız.',back:'‹ Daha Fazla',cancel:'Vazgeç',save:'Kaydet',retry:'Tekrar dene',encryptedBackup:'Şifreli yedek dışa aktar',restoreBackup:'Şifreli yedeği geri yükle',csvWarning:'CSV şifreli değildir. Dosyaya sahip herkes okuyabilir.',todayFocus:'Bugünün odağı',birthdays:'Yaklaşan doğum günleri',noBirthdays:'Önümüzdeki 30 günde doğum günü yok.',statStrong:'Güçlü',todaySection:'Bugün',followUpsCount:(n:number)=>`${n} takip`,followUpPrefix:'Takip',quietDay:'Sakin bir gün. Sonraki takibin burada görünecek.',recentlyAdded:'Son eklenenler',seeThreadTitle:'Bağlantıyı görün.',shortestPath:'EN KISA YOL',degreesAway:(n:number)=>`${n} derece uzakta`,noConnectionSix:'Altı derece içinde bağlantı bulunamadı',tryAnother:'Başka birini dene veya eksik ilişkiyi ekle.',focusLabel:'ODAK',findPath:'Yol bul',profileLink:'Profil ›',chooseStarting:'Bir başlangıç noktası seç',buildMap:'Tanıdığın birinden canlı bir harita oluştur.',findPerson:'Kişi bul',connectionDefault:'Bağlantı',setAsDestination:'Hedef olarak ayarla',inNeighborhood:'bu çevrede',relToday:'Bugün',relYesterday:'Dün',relDaysAgo:(n:number)=>`${n} gün önce`,relMonthsAgo:(n:number)=>`${n} ay önce`,relYearsAgo:(n:number)=>`${n} yıl önce`,noContactYet:'Henüz temas yok'}
} as const;
export type TranslationKey = keyof typeof text.en;
export function useTranslation(){const language=useAppStore(s=>s.language);return {language,t:(key:TranslationKey,...args:number[])=>{const table=text[language] as Record<string,string|((n:number)=>string)>;const fallback=text.en as Record<string,string|((n:number)=>string)>;const value=(table[key]??fallback[key]) as string|((n:number)=>string)|undefined;if(!value)return key;return typeof value==='function'?value(args[0]??0):value;}};}
export async function saveLanguage(language:Language){await AsyncStorage.setItem('networkos.language',language);useAppStore.getState().setLanguage(language);}
export function systemLanguage():Language{try{const locale=Intl.DateTimeFormat().resolvedOptions().locale?.toLowerCase()??'en';return locale.startsWith('tr')?'tr':'en';}catch{return 'en';}}
export async function loadLanguage(){const language=await AsyncStorage.getItem('networkos.language');if(language==='en'||language==='tr'){useAppStore.getState().setLanguage(language);return;}useAppStore.getState().setLanguage(systemLanguage());}
